import React from 'react';
import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '@/constants/theme';
import { useBackNavigation } from '@/hooks/useBackNavigation';
import { fontFamily } from '@/constants/typography';

export default function PrivacyPolicyScreen() {
  const goBack = useBackNavigation('/(home)/profile');

  return (
    <SafeAreaView edges={['top']} style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={goBack} style={styles.backButton}>
          <Ionicons name='arrow-back' size={24} color={colors.onSurface} />
        </Pressable>
        <Text style={styles.headerTitle}>Privacy Policy</Text>
        <View style={styles.placeholder} />
      </View>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.h1}>Privacy Policy</Text>
        <Text style={styles.p}>Last updated: June 11, 2026</Text>
        <Text style={styles.p}>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </Text>
        <Text style={styles.p}>
          We use Your Personal Data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </Text>

        <Text style={styles.h2}>Interpretation and Definitions</Text>
        <Text style={styles.h3}>Interpretation</Text>
        <Text style={styles.p}>
          The words whose initial letters are capitalized have meanings defined
          under the following conditions. The following definitions shall have
          the same meaning regardless of whether they appear in singular or in
          plural.
        </Text>

        <Text style={styles.h3}>Definitions</Text>
        <Text style={styles.p}>For the purposes of this Privacy Policy:</Text>
        <View style={styles.bulletList}>
          <Text style={styles.li}>
            • <Text style={styles.bold}>Account</Text> means a unique account
            created for You to access our Service or parts of our Service.
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>Application</Text> refers to Grab it,
            the software program provided by the Company.
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>Company</Text> (referred to as either
            {"\"the Company\", \"We\", \"Us\" or \"Our\""} in this Privacy Policy) refers to
            Grab it.
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>Country</Text> refers to: Uttar Pradesh,
            India
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>Device</Text> means any device that can
            access the Service such as a computer, a cell phone or a digital
            tablet.
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>Personal Data</Text> is any information
            that relates to an identified or identifiable individual.
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>Service</Text> refers to the
            Application.
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>Usage Data</Text> refers to data
            collected automatically, either generated by the use of the Service
            or from the Service infrastructure itself.
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>You</Text> means the individual
            accessing or using the Service.
          </Text>
        </View>

        <Text style={styles.h2}>Collecting and Using Your Personal Data</Text>
        <Text style={styles.h3}>Types of Data Collected</Text>
        <Text style={styles.h4}>Personal Data</Text>
        <Text style={styles.p}>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </Text>
        <View style={styles.bulletList}>
          <Text style={styles.li}>• Email address</Text>
          <Text style={styles.li}>• First name and last name</Text>
          <Text style={styles.li}>
            • Address, State, Province, ZIP/Postal code, City
          </Text>
        </View>

        <Text style={styles.h4}>
          Information Collected while Using the Application
        </Text>
        <Text style={styles.p}>
          While using Our Application, in order to provide features of Our
          Application, We may collect, with Your prior permission:
        </Text>
        <View style={styles.bulletList}>
          <Text style={styles.li}>• Information regarding your location</Text>
          <Text style={styles.li}>
            • Pictures and other information from your Device&apos;s camera and photo
            library
          </Text>
        </View>
        <Text style={styles.p}>
          We use this information to provide features of Our Service, to improve
          and customize Our Service. You can enable or disable access to this
          information at any time, through Your Device settings.
        </Text>

        <Text style={styles.h3}>Use of Your Personal Data</Text>
        <Text style={styles.p}>
          The Company may use Personal Data for the following purposes:
        </Text>
        <View style={styles.bulletList}>
          <Text style={styles.li}>
            •{' '}
            <Text style={styles.bold}>To provide and maintain our Service</Text>
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>To manage Your Account</Text>
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>To contact You</Text> regarding updates
            or informative communications.
          </Text>
          <Text style={styles.li}>
            • <Text style={styles.bold}>To manage Your requests</Text>
          </Text>
        </View>

        <Text style={styles.h3}>Delete Your Personal Data</Text>
        <Text style={styles.p}>
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You.
        </Text>
        <Text style={styles.p}>
          Our Service may give You the ability to delete certain information
          about You from within the Service by visiting your account settings.
        </Text>

        <Text style={styles.h2}>Contact Us</Text>
        <Text style={styles.p}>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </Text>
        <View style={styles.bulletList}>
          <Text style={styles.li}>• By email: anuj846k@gmail.com</Text>
        </View>

        {/* Extra spacing at the bottom */}
        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontFamily: fontFamily.display,
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  placeholder: {
    width: 40,
  },
  content: {
    padding: 24,
  },
  h1: {
    fontFamily: fontFamily.display,
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.onSurface,
    marginBottom: 16,
  },
  h2: {
    fontFamily: fontFamily.display,
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.onSurface,
    marginTop: 24,
    marginBottom: 12,
  },
  h3: {
    fontFamily: fontFamily.display,
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.onSurface,
    marginTop: 16,
    marginBottom: 8,
  },
  h4: {
    fontFamily: fontFamily.label,
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.onSurfaceVariant,
    marginTop: 12,
    marginBottom: 8,
  },
  p: {
    fontFamily: fontFamily.body,
    fontSize: 15,
    color: colors.onSurfaceVariant,
    lineHeight: 24,
    marginBottom: 16,
  },
  bulletList: {
    marginBottom: 16,
    paddingLeft: 8,
  },
  li: {
    fontFamily: fontFamily.body,
    fontSize: 15,
    color: colors.onSurfaceVariant,
    lineHeight: 24,
    marginBottom: 8,
  },
  bold: {
    fontWeight: 'bold',
    color: colors.onSurface,
  },
});
